Very basic smelting (ores to bars) script
chsami/Microbot pull request #337
Opened 2024-07-16 20:46 UTC by vincentmathis

Depending on the selected bar type it will fetch inventory full of ores/coals in the right ratio from the bank, walk back to the furnace where the script was started, smelt everything, bank the bars, repeat.

I don't have an account to test anything but bronze bars in Lumbridge so there might be bugs with higher smithing levels.

It's really rudimentary as I have zero experience with runelite/microbot before writing this today.

2024-07-17 19:03 UTC, chsami requested changes

2024-07-17 19:03 UTC, chsami commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/smelting/AutoSmeltingPlugin.java
> +        name = PluginDescriptor.Default + "Auto Smelting",
Please add your name to the plugin descriptor

2024-07-17 19:04 UTC, chsami reviewed
Please make a PR to development

2024-07-18 12:01 UTC, vincentmathis commented
> Please make a PR to development

closing this because of wrong branch, new PR https://github.com/chsami/microbot/pull/339

2024-07-18 12:01 UTC, closed without merging