Pie Baker
chsami/Microbot pull request #345
Opened 2024-07-24 01:12 UTC by bttqjs

The Pie Baker Plugin automates baking pies in OSRS using the Lunar spellbook's Bake Pie spell. 
It allows users to select from various raw pies, automatically withdraws them from the bank, casts the spell to bake them, and deposits the cooked pies. 
The plugin supports tick-perfect casting for efficiency and tracks Magic and Cooking XP per hour. 
Users can view the selected pie and XP rates via an in-game overlay. 

Instructions:
Ensure you have the required runes in your inventory and start the bot at any bank, preferably a populated one like the Grand Exchange.

2024-07-28 17:55 UTC, chsami requested changes

2024-07-28 17:55 UTC, chsami commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/piebaker/PieBakerPlugin.java
> +        name = "Pie Baker",
Add your name in the plugindescriptor and prepend it in the script name, this way people know who made the plugin and can contact you if necessary.

2024-07-28 21:46 UTC, bttqjs reviewed
Updated

2024-07-29 09:22 UTC, bttqjs reviewed
i see B is already taken so i choosed J

2024-07-29 12:16 UTC, bttqjs commented
Added **Flippers Chaser**
This plugin automates the process of obtaining Flippers from Mogres by utilizing fishing explosives and handling combat scenarios. Additionally, it integrates Discord notifications to keep players informed about the plugin's success or failure.

- Automated Combat
- Prayer Management
- Food Consumption
- Discord Notifications
- Automatic Logout or Teleport

The plugin will automatically use fishing explosives on the "Ominous Fishing Spot" to spawn Mogres.
Upon spawning, the plugin will engage and kill the Mogres.
The plugin will loot Flippers and then teleport to your house or log out if a house teleport tab is unavailable.
Discord notifications will inform you of the outcome, including a screenshot for success or failure.

Added also discord notification embeds:
`[Success] **Player name** has obtained **Flippers** successfully!
`
`[Failure] **Player name** has no food in inventory, logging out.
`
Contributions are welcome!

2024-07-29 13:48 UTC, bttqjs commented
I joined discord 
![image](https://github.com/user-attachments/assets/d3e4550e-279c-4479-bda3-77f298ccd7bc)

2024-07-29 19:51 UTC, chsami approved these changes

2024-07-29 20:22 UTC, chsami commented
There are still some errors in the flipper plugin about discord.

2024-07-29 21:19 UTC, bttqjs commented
Nested DiscordWebhook class for simplicity in Plugin file

2024-07-30 12:11 UTC, merged