ShootingStar Plugin + Implement Antiban Features for plugins
chsami/Microbot pull request #377
Opened 2024-09-05 06:54 UTC by g-mason0

I want to apologize in advance for adjusting various things in this PR, I tried to focus this as best I could but I am just happy to get this merged!

Implemented Antiban Features on the following plugins:
1. Nate's AutoFishing Plugin
2. AutoCooking Plugin
3. AutoLooter Plugin
4. AutoWoodcutting Plugin

ShootingStar Plugin -

[Showcase](https://azpublicfiles.blob.core.windows.net/uploads/java_NrtJdLa6eT.mp4)

The ShootingStar plugin is a star finder/auto star miner plugin. It leverages public data about scouted crashed stars & it will match those locations with some static game static & some checks around the player to confirm build a panel that the user can select stars from, walk to & mine them.

This plugin has two modes:
1. Manual Mode - This allows for single trip mining sessions, you will be directed to the bank & then you will be able to select a star in the panel to star heading to this star & mining it
2. Use Nearest High Tier Star - This is a fully automatic mode. This will check the distance of stars from an acceptable tier range & map them based on distance, then select the closest star that is the highest tier.

This plugin supports inventory setups, by default it uses an inventory setup name called "Shooting Star" but this is configurable in the plugin settings. It has been tested for many edge cases & when not using inventory setups the only inventory requirement is a pickaxe.

Other changes:
AutoCookingScript: Removed Pizza's ( going to merge this function into a baking script that is apart of the cooking plugin )
AutoFishingScript: Added Cave Eels
Rs2Player: adjusted waitForXPDrop methods to rely on each other & added shortestDistanceTo to check distance using ShortestPathPlugin (this method can take some time to return)

2024-09-05 13:35 UTC, g-mason0 commented
I apologize for the last second changes, I had found that when there is a lot of stars in your acceptable tier range the Rs2Player.shortestDistanceTo seems to take a bit to perform that many pathing calculations at once - so I added a check to see if the distance already exists before calculating.

2024-09-07 18:20 UTC, chsami requested changes

2024-09-07 18:20 UTC, chsami commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/util/walker/Rs2Walker.java
> +    public static int shortestDistanceTo(WorldPoint startpoint, WorldPoint endpoint) {
shortestDistanceTo is not a clear method name. I would suggest getDistanceBetween(WorldPoint startPoint, WorldPoint endPoint)

2024-09-07 18:23 UTC, g-mason0 commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/util/walker/Rs2Walker.java
> +    public static int shortestDistanceTo(WorldPoint startpoint, WorldPoint endpoint) {
This has been updated!

2024-09-07 18:29 UTC, g-mason0 commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/util/walker/Rs2Walker.java
> +    public static int shortestDistanceTo(WorldPoint startpoint, WorldPoint endpoint) {
One last change :( I changed didn't change the Rs2Player method

2024-09-07 18:30 UTC, chsami approved these changes

2024-09-07 18:32 UTC, chsami commented
Thank you so much for your significant contribution! I really appreciate the plugin and the effort you put into it. A special thanks as well for providing a video demonstration and a thorough explanation—it was very helpful!

2024-09-07 18:32 UTC, merged