INIT BlastoiseFurnace
chsami/Microbot pull request #386
Opened 2024-09-16 13:39 UTC by FunkyRhythm

Blast Furnace plugin;
description:
this plugin will handle blast furnace in a BF world , wont pay coffer or foremen.

works for : gold, steel, mithril, adamant, rune.
requires: ice gloves/goldsmiths gloves and a coal bag

a new sleepuntil method was added to script.java for some functionality to work properly

DEMO:
https://youtu.be/iyAOluFEpy8

2024-09-21 17:44 UTC, chsami requested changes

2024-09-21 17:44 UTC, chsami commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/Script.java
> +    public boolean sleepUntil(BooleanSupplier awaitedCondition, BooleanSupplier resetCondition, int timeout) {
Why do you add an extra sleepuntil here? Cant you just use thé existing one by combining the await and reset condition in one boolean supplier?

2024-09-21 17:44 UTC, chsami commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/blastoisefurnace/BlastoiseFurnaceConfig.java
> +        return "must have Ice Gloves or smiths gloves (i) equiped\n+\ncoalbag, stamina potions and energy potions in bank\n\n| if doing gold bars; must have Goldsmiths Gauntlet and bank your coalbag
We have a configinformation where you can put the script information in.

2024-09-21 17:44 UTC, chsami commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/blastoisefurnace/BlastoiseFurnaceOverlay.java
> +//
It seems that you decompiled these classes. Where do you get thé code from?

2024-09-21 21:27 UTC, FunkyRhythm commented
testing

2024-09-22 08:27 UTC, chsami approved these changes

2024-09-22 08:30 UTC, merged