Tutorial Island
chsami/Microbot pull request #427
Opened 2024-10-19 22:06 UTC by g-mason0

In this iteration of this script I have made the following adjustments:

1. Added Random Chance to change gender from current gender
2. Added Random Chance to change pronouns from current pronouns

I also added a helper method into Rs2UIHelper to strip the col tags from text, just figured this could be useful elsewhere..

2024-10-19 22:14 UTC, g-mason0 commented
1 last change, I had forgotten my adjustments for the mage guide!

2024-10-21 05:33 UTC, chsami requested changes

2024-10-21 05:33 UTC, chsami commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/tutorialisland/TutorialIslandScript.java
> +            if (distance >= 4) {
this should be greater than 4.  because the webwalker will not execute if the distance is 4.
 
This is the check of the web webwalker:
Rs2Player.getWorldLocation().distanceTo(target) <= distance

2024-10-21 05:36 UTC, chsami commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/tutorialisland/TutorialIslandScript.java
> +            if (distance >= 4) {
or better would be to 

if (Rs2Walker.walkTo(targetPoint, 4) && Rs2Npc.interact(npc, "Talk-to")) {
    sleepUntil(Rs2Dialogue::isInDialogue);
}

2024-10-21 22:49 UTC, g-mason0 commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/tutorialisland/TutorialIslandScript.java
> +            if (distance >= 4) {
I just increased the range to satisfy the walker requirements, this way it also clicks on the NPC before being so close to the mage guide

2024-10-22 10:02 UTC, chsami requested changes

2024-10-22 10:02 UTC, chsami commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/tutorialisland/TutorialIslandScript.java
> +            if (distance >= 8) {
this has to be > 8, otherwise it can get stuck in an infinite loop, because the walker will not walk if it is equal to 8

2024-10-22 12:42 UTC, gmason0 commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/tutorialisland/TutorialIslandScript.java
> +            if (distance >= 8) {
I am sorry, I guess I misunderstood what you were saying before.. Its been changed

2024-10-23 03:06 UTC, chsami approved these changes

2024-10-23 03:06 UTC, merged