Herbrun updates, Wilderness check for blighted food/potions + seed pod teleport
chsami/Microbot pull request #443
Opened 2024-10-29 11:35 UTC by yairtu

- added wilderness check for blighted food and prayer potions
-  seedpod teleport + wilderness check in playeralarm
- added support for toggle location in herbrun
-  added harmony support
- added added info to plugin as well as migrating guide to ConfigInformation panel
- added farming cape support

2024-10-30 06:15 UTC, chsami requested changes

2024-10-30 06:15 UTC, chsami commented on .run/Runelite.run.xml
You can't be changing the runelite.run.xml for everyone else. Please remove this change

2024-10-30 06:15 UTC, chsami commented on hs_err_pid23568.log
This file can be left out of your PR aswell

2024-10-30 08:07 UTC, yairtu commented on .run/Runelite.run.xml
Im not sure how it got added again, I will add it to gitignore

2024-10-30 08:09 UTC, yairtu commented on hs_err_pid23568.log
Should I delete it ?

2024-10-30 21:10 UTC, chsami commented on hs_err_pid23568.log
yes

2024-10-31 15:13 UTC, chsami approved these changes

2024-10-31 15:14 UTC, chsami approved these changes

2024-10-31 15:14 UTC, merged