Gabulhas/karambwans and gold bars
chsami/Microbot pull request #460
Opened 2024-11-02 16:37 UTC by Gabulhas

This includes

- Karambwan fishing script (useful for ironmen)
    - basically fishes at karambwans spot, uses fairy ring to go to zanaris to bank
    - it uses zanaris instead of other fairy ring (ex: closer to a bank) because it's the most afk (and less detectable way) to do so
    - TODO: automatically get more karambwaji (bait) and use the fish barrel
    
- Gold bars at Blast furnace
    - Simple but works
    - No stamina support

2024-11-02 20:10 UTC, chsami requested changes

2024-11-02 20:10 UTC, chsami commented on .run/Runelite.run.xml
Please exclude this file, you cannot change this file for everyone else.

2024-11-02 20:10 UTC, chsami commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/gabplugs/goldrush/GabulhasGoldRushConfig.java
> +    @ConfigItem(
Please use @ConfigInformation("") under the @ConfigGroup for your script description. Please give a small explanation what the script does and what the requirements are.

The @ConfigInformation tag supports html

2024-11-02 20:10 UTC, chsami commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/gabplugs/karambwans/GabulhasKarambwansConfig.java
> +    @ConfigItem(
Please use @ConfigInformation("") under the @ConfigGroup for your script description. Please give a small explanation what the script does and what the requirements are.

The @ConfigInformation tag supports html

2024-11-03 06:19 UTC, chsami commented on .run/Runelite.run.xml
> +</component>
there is still a change here, This file cannot be in the PR, please put it back to the original

2024-11-03 06:20 UTC, chsami requested changes
Runelite.run.xml is still in the changes, please revert this back to the original so it does not show up as a changed file

2024-11-03 20:54 UTC, chsami commented on .run/Runelite.run.xml
You deleted the file, you have to remove the file from your changes.

Simply just take the original file and push it to your branch

2024-11-03 20:55 UTC, chsami reviewed
other than the runelite.run.xml that has been deleted this is good to go. Please push the file back to the repo with its original content

2024-11-04 22:32 UTC, Gabulhas commented
Add two more scripts
Super glass make script, that uses either Giant seaweed and normal seaweed.
Sand miner that all it does is mine sandstone and deposits the sand in the quarry.

2024-11-05 07:35 UTC, chsami requested changes

2024-11-05 07:35 UTC, chsami commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/gabplugs/glassmake/GabulhasGlassMakeScript.java
There's already a glassblowing script under the craftingplugin, add onto it, but we try to avoid adding duplicate plugins to not have a giant list of plugins

2024-11-07 04:36 UTC, chsami approved these changes

2024-11-07 04:48 UTC, merged