ClueSolver V2 - Massively refactored to not use reflection
chsami/Microbot pull request #501
Opened 2024-11-17 00:41 UTC by Budbomber

No longer using reflection, solely relies on the cluescroll plugin - Have moved it and changed everything that we will need to public, base is pretty much sorted, couple of key things left to do which include

- Firming up walking logic, walker to get there, upon success fastwalk canvas to precise loc, some clues will need defined areas etc as to make walker not fire again until needed.

- Overal logic of the clues needs improving (Currently only been testing on mediums) But the general flow of clues can differ from (Easy, med, hard, elite, master) Ideally each of our tasks "Should" be able to cover this for whatever type of clue.

- Implement custom overlay, (task state, runtime, value gained, collections logged etc)

- Add further clue tasks, MapClues,  Cipher clues, ThreeStep, Skill challenge (Charlie or falo etc) Implement the logic for fairy ring clues and music clues

-  Find a way of getting feedback whether from discord or create a simple logging system that will save debug logs for users on the jar etc. 

- LOTS MORE

2024-11-17 12:05 UTC, chsami requested changes
it seems like you deleted the runelite.run.xml, please undo this

2024-11-17 12:18 UTC, Budbomber reviewed
Sorry, appears I forgot to add both of the run xml's both re-added

2024-11-17 14:59 UTC, chsami requested changes
please  put back the proxy settings as an example for the proxy.run.xml

2024-11-17 14:59 UTC, chsami commented on .run/Runelite with proxy.run.xml
> -    <option name="PROGRAM_PARAMETERS" value="-developer-mode -proxy=144.49.99.215:8080 -proxy-type=http" />
please  put back the proxy settings as an example for the proxy.run.xml

2024-11-17 22:12 UTC, chsami requested changes

2024-11-17 22:12 UTC, chsami commented on .run/Runelite.run.xml
> +        <option name="ALTERNATIVE_JRE_PATH" value="temurin-23"/>
temurin-23 should be set back to "11"

2024-11-17 23:07 UTC, chsami approved these changes

2024-11-17 23:10 UTC, chsami commented
hmm your build is failing, please take a look

2024-11-17 23:10 UTC, chsami requested changes
build failed

2024-11-18 14:52 UTC, Budbomber reviewed
As far as i'm aware, all is good build is fine correct runs etc.

2024-11-19 05:07 UTC, chsami approved these changes

2024-11-19 05:08 UTC, merged