Wrong operator for fourth item check in BankStander
chsami/Microbot pull request #517
Opened 2024-11-21 21:14 UTC by lVidStorm

2024-11-21 21:18 UTC, g-mason0 commented on runelite-client/src/main/java/net/runelite/client/plugins/microbot/bankjs/BanksBankStander/BanksBankStanderScript.java
> +            } else if (fourthItemId == null || (Rs2Bank.count(fourthItemIdentifier) + Rs2Inventory.count(fourthItemIdentifier)) >= config.fourthItemQuantity()) {
According to 00's message, the second portion of the || operator should also be updated to be like the other items.

`fourthItemId == null && (Rs2Bank.count(fourthItemIdentifier) + Rs2Inventory.count(fourthItemIdentifier)) **<** config.fourthItemQuantity()`

2024-11-22 20:18 UTC, chsami approved these changes

2024-11-22 20:19 UTC, chsami requested changes
see comment george

2024-11-22 20:28 UTC, g-mason0 commented
@chsami - this looks to be corrected

2024-11-22 22:33 UTC, chsami approved these changes

2024-11-22 22:34 UTC, merged