Fixed BirdHunter
chsami/Microbot pull request #523
Opened 2024-11-26 10:43 UTC by lhndl93

Switched the IDS again, they like changing them back and forth

2024-11-26 13:04 UTC, chsami commented
Use ObjectID instead of a magic number

2024-11-26 13:05 UTC, chsami requested changes
Use ObjectID of itemid instead of magic numbers

2024-11-26 13:18 UTC, changednamedes commented
> Use ObjectID of itemid instead of magic numbers

Done

2024-11-27 05:17 UTC, chsami approved these changes

2024-11-27 05:17 UTC, merged